//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3625
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USB_IR_REMOCON_CT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO01 {
            get {
                return ((string)(this["MEMO01"]));
            }
            set {
                this["MEMO01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO02 {
            get {
                return ((string)(this["MEMO02"]));
            }
            set {
                this["MEMO02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO03 {
            get {
                return ((string)(this["MEMO03"]));
            }
            set {
                this["MEMO03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO04 {
            get {
                return ((string)(this["MEMO04"]));
            }
            set {
                this["MEMO04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO05 {
            get {
                return ((string)(this["MEMO05"]));
            }
            set {
                this["MEMO05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO06 {
            get {
                return ((string)(this["MEMO06"]));
            }
            set {
                this["MEMO06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO07 {
            get {
                return ((string)(this["MEMO07"]));
            }
            set {
                this["MEMO07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO08 {
            get {
                return ((string)(this["MEMO08"]));
            }
            set {
                this["MEMO08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO09 {
            get {
                return ((string)(this["MEMO09"]));
            }
            set {
                this["MEMO09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO10 {
            get {
                return ((string)(this["MEMO10"]));
            }
            set {
                this["MEMO10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO11 {
            get {
                return ((string)(this["MEMO11"]));
            }
            set {
                this["MEMO11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO12 {
            get {
                return ((string)(this["MEMO12"]));
            }
            set {
                this["MEMO12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO13 {
            get {
                return ((string)(this["MEMO13"]));
            }
            set {
                this["MEMO13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO14 {
            get {
                return ((string)(this["MEMO14"]));
            }
            set {
                this["MEMO14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO15 {
            get {
                return ((string)(this["MEMO15"]));
            }
            set {
                this["MEMO15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO16 {
            get {
                return ((string)(this["MEMO16"]));
            }
            set {
                this["MEMO16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO17 {
            get {
                return ((string)(this["MEMO17"]));
            }
            set {
                this["MEMO17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO18 {
            get {
                return ((string)(this["MEMO18"]));
            }
            set {
                this["MEMO18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO19 {
            get {
                return ((string)(this["MEMO19"]));
            }
            set {
                this["MEMO19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ")]
        public string MEMO20 {
            get {
                return ((string)(this["MEMO20"]));
            }
            set {
                this["MEMO20"] = value;
            }
        }
    }
}
